name: Scott Doxey
markdown: kramdown
permalink: articles/:title
url: http://neo-geek.net

description: My name is **Scott Doxey** and this is my online space. Here you will find my musings on certain topics that interest me, information about projects I've work on, talks I've given, and photos I have taken. I am a full-stack developer working primarily in Node.js and JavaScript. I have developed and released many open source projects, all available on [GitHub](https://github.com/neogeek) and [NPM](http://npmjs.com/~neogeek). I currently work at [Cantina](http://cantina.co/) in downtown Boston as a User Experience consultant. In addition to web development I also like to build and play video games.
